---
- name: Install Elasticsearch
  yum:
    name: elasticsearch
- name: Set network.host
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "^#?\\s?network.host:"
    line: "network.host: 0.0.0.0"
- name: Set heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: "^-Xms", line: "-Xms1g" }
  - { regexp: "^-Xmx", line: "-Xmx1g" }
- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
